export const MEDITATION_QUOTES = [
  'Breathe in peace, breathe out chaos.',
  'The present moment is your point of power.',
  'Stillness is the key to knowing yourself.',
  'Inhale the future, exhale the past.',
  'Peace comes from within.',
  'Let go of what was, be open to what is.',
  'Quiet the mind, and the soul will speak.',
  'Each breath is a new beginning.',
  'Find stillness in busy moments.',
  'The soul knows how to heal itself.',
  'In silence, find your answers.',
  'Be here now, fully present.',
  'The mind is everything.',
  'Calm mind brings inner strength.',
  'From sound to silence.',
  'The quieter you become, the more you hear.',
  'Your calm mind is your superpower.',
  'Joy lives in the present moment.',
  'Breathe deeply, release expectations.',
  'Peace comes from within your mind.',
  "Sit still and know you're enough.",
  'Thoughts are just visitors.',
  "Meditation is recognizing you're more than your thoughts.",
  'Each minute is an unrepeatable miracle.',
  'Breathing is my anchor.',
  'Be where you are, or miss your life.',
  'Capture moments by paying attention.',
  'Mindfulness is simple but not always easy.',
  'Little moments are everything.',
  'Now is the only moment we control.',
  'See the difference between reality and story.',
  'Be fully awake in your life.',
  'The mind is like water - calm it to see clearly.',
  'Your life is your meditation.',
  "Learn to ride life's waves.",
  'Movement for body, stillness for mind.',
  'Feelings are temporary visitors.',
  'Befriend yourself and your experience.',
  'The future is built on present moments.',
  'In rushing, we forget to be.',
  'Your presence is your greatest gift.',
  'Walk gently on the earth.',
  'Smile, breathe, go slowly.',
  'Happiness is here and now.',
  "Don't wait to be happy.",
  'Morning brings new possibilities.',
  'Breath connects body and mind.',
  'Awareness makes actions sacred.',
  'Peace comes from walking your path.',
  'Beauty is being yourself.',
  'Let go to be free.',
  'Alive means anything is possible.',
  'Love grows when shared.',
  'Suffering comes from fear of change.',
  'Missing the present means missing life.',
  'Hurt people hurt people.',
  'Presence is the best gift.',
  'Happy parents raise happy children.',
  'Every moment holds possibilities.',
  'True understanding comes from unlearning.',
  "The past is gone, the future isn't here.",
  'Suffering is optional.',
  'We are all connected.',
  'Beauty is being authentic.',
  'Now is all we truly have.',
  'The future is built now.',
  'Slow down to feel alive.',
  'Your attention is powerful.',
  'Step lightly on the earth.',
  'Breathe and smile.',
  'Joy is in this moment.',
  "Don't postpone happiness.",
  'Each morning is a new chance.',
  'Breathe to connect within.',
  'Mindfulness makes life sacred.',
  'Peace comes from within.',
  'Be yourself, always.',
  'Freedom is in letting go.',
  'Life is full of possibilities.',
  'Sharing love multiplies it.',
  'Change is the only constant.',
  'Be fully present now.',
  'Pain often comes from pain.',
  'Be there for others.',
  'Happiness is contagious.',
  'Opportunities are everywhere.',
  'Unlearn to truly understand.',
  'The past is just a memory.',
  'You choose your suffering.',
  "We're all one.",
  'Authenticity is beautiful.',
  'Now is all there is.',
  'Build your future now.',
  'Slow down to speed up.',
  'Where attention goes, energy flows.',
];
